version: '2.0'

services:
  db:
    image: postgres
    restart: always
    ports: 
      - '5431:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'database'
    volumes:
      - ./data/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080